# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Anasayfa"
  url = "#about"
  weight = 10

[[main]]
  name = "Yazılar"
  url = "#posts"
  weight = 20

[[main]]
  name = "Projeler"
  url = "#projects"
  weight = 30

[[main]]
  name = "Etkinlikler"
  url = "#talks"
  weight = 40
  
[[main]]
  name = "Yayınlar"
  url = "#publications"
  weight = 50

[[main]]
  name = "İletişim"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
